import "../../globals.css";
import {TopicsProvider} from "@/contexts/TopicsContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <TopicsProvider>
      {children}
    </TopicsProvider>
    </body>
    </html>
  )
}
