services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: knowledge
    volumes:
      - mongodb_data:/data/db

  spring-boot-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:toor@mongodb:27017/knowledge

  react-app:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  mongodb_data:
